image: java:8

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Testing the app"
    - ./gradlew test

build:
  stage: build
  script:
    - echo "Building the app"
    - ./gradlew clean build

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/staging-welcome-app.git
    - git push heroku master
  environment:
    name: staging
    url: https://staging-welcome-app.herokuapp.com/
  only:
  - master

deploy_prod:
  stage: deploy
  image: ruby:2.5
  script:
    - echo "Deploy to production server"
    - gem install dpl
    - dpl --provider=heroku --app=production-welcome-app --api-key=$HEROKU_API_KEY
  environment:
    name: production
    url: https://production-welcome-app.herokuapp.com/
  when: manual
  only:
  - master
